name: main-5_6

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-5_6:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read PHP version - revision
        uses: bfren/read-file-action@v1
        with:
          path: ./5.6/PHP_REVISION
        id: php_revision
      -
        name: Read image version
        uses: bfren/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./5.6/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bcgdesign/apache-php:latest
            bcgdesign/apache-php:${{ steps.version.outputs.content }}
            bcgdesign/apache-php:php5
            bcgdesign/apache-php:php5-${{ steps.version.outputs.content }}
            bcgdesign/apache-php:php5.6
            bcgdesign/apache-php:php5.6-${{ steps.version.outputs.content }}
            bcgdesign/apache-php:php${{ steps.php_revision.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
